### ISSUE TITLE
KITTI360  DataLoader error

### ISSUE THREAD

**Issue by NathanDrake67** [kazuto1011/r2dm#5]
Hi, I am trying to reproduce your work. Can I put KITTI360 data directly into the data/kitti_160/dataset folder instead of making a soft link? By the way, could you give **a brief example of folder structure?** 

Now I have put the data like :

`~/r2dm-main/data/kitti_360/dataset/KITTI-360/data_3d_raw/2013_05_28_drive_0000_sync/velodyne_points/data/00000000000.bin,00000000001.bin……`

However, when I run  " `accelerate launch train.py` " as in the ReadMe

The terminal shows:

```powershell
set HDL-64E linear ray angles
number of parameters: 31,099,650
Dataset({
    features: ['sample_id', 'xyz', 'reflectance', 'depth', 'mask'],
    num_rows: 0
})
Traceback (most recent call last):
  File "~/r2dm-main/train.py", line 308, in <module>
    train(cfg)
  File "~/r2dm-main/train.py", line 166, in train
    dataloader = DataLoader(
  File "/home/qbk/anaconda3/envs/r2dm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 349, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/qbk/anaconda3/envs/r2dm/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 140, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
**ValueError: num_samples should be a positive integer value, but got num_samples=0**
``` 

It seems like the DataLoader cannot load any data, I want to know how to use it correctly.
Thank you!

**Comment by kazuto1011** [comment]
Yes, you can put the data directly. The expected path is like:
https://github.com/kazuto1011/r2dm/blob/027674e84354408e954cc5b9542b74331b6645eb/data/kitti_360/kitti_360.py#L104
`KITTI-360` is unnecessary in your case.

**Comment by NathanDrake67** [comment]
Thanks a lot. Now I have already set my data dir like:
![0313](https://github.com/kazuto1011/r2dm/assets/61680773/f5540f90-b2b4-460f-80c9-cf26d2ca5fd9)

But when I run `accelerate launch train.py`
The terminal still displays an error
```powershell

(r2dm) qbk@qbk-Legion:~/Documents/r2dm-main$ accelerate launch train.py
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
TrainingConfig(dataset='kitti_360', image_format='log_depth', lidar_projection='spherical-1024', train_depth=True, train_reflectance=True, resolution=(64, 1024), batch_size_train=8, batch_size_eval=8, num_workers=4, num_steps=300000, save_image_steps=5000, save_model_steps=10000, gradient_accumulation_steps=1, criterion='l2', lr=0.0001, lr_warmup_steps=10000, adam_beta1=0.9, adam_beta2=0.99, adam_weight_decay=0.0, adam_epsilon=1e-08, ema_decay=0.995, ema_update_every=10, output_dir='logs/diffusion', seed=0, mixed_precision='fp16', dynamo_backend='inductor', model_name='efficient_unet', model_base_channels=64, model_temb_channels=None, model_channel_multiplier=(1, 2, 4, 8), model_num_residual_blocks=3, model_gn_num_groups=8, model_gn_eps=1e-06, model_attn_num_heads=8, model_coords_embedding='fourier_features', model_dropout=0.0, diffusion_num_training_steps=1024, diffusion_num_sampling_steps=128, diffusion_objective='eps', diffusion_beta_schedule='cosine', diffusion_timesteps_type='continuous')
set HDL-64E linear ray angles
number of parameters: 31,099,650
Dataset({
    features: ['sample_id', 'xyz', 'reflectance', 'depth', 'mask'],
    num_rows: 0
})
Traceback (most recent call last):
  File "/home/qbk/Documents/r2dm-main/train.py", line 308, in <module>
    train(cfg)
  File "/home/qbk/Documents/r2dm-main/train.py", line 166, in train
    dataloader = DataLoader(
  File "/home/qbk/anaconda3/envs/r2dm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 349, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/qbk/anaconda3/envs/r2dm/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 140, in __init__
    raise ValueError(f"num_samples should be a positive integer value, but got num_samples={self.num_samples}")
ValueError: num_samples should be a positive integer value, but got num_samples=0
Traceback (most recent call last):
  File "/home/qbk/anaconda3/envs/r2dm/bin/accelerate", line 10, in <module>
    sys.exit(main())
  File "/home/qbk/anaconda3/envs/r2dm/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/qbk/anaconda3/envs/r2dm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 986, in launch_command
    simple_launcher(args)
  File "/home/qbk/anaconda3/envs/r2dm/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/qbk/anaconda3/envs/r2dm/bin/python3.10', 'train.py']' returned non-zero exit status 1.

``` 

It seems the Dataloader still got nothing, and it seems like the  **kitti_360.py** was not launched in **train.py**, is there a problem here? 
Thank you!

**Comment by kazuto1011** [comment]
Please try removing the cache under `~/.cache/huggingface/datasets` or `$HF_DATASETS_CACHE` if you have set it.

**Comment by NathanDrake67** [comment]
After I removed the cache, the problem has been resolved, thank you very much!
